name: QA check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install numpy
          pip install inotify
      - run: sudo apt update
      - uses: actions/checkout@v3
      - run: python .github/workflows/inotify_script.py /home/runner/work/Algorithms/Algorithms /home/runner/inotify-logs.csv & echo 'optimizing-ci-builds'
      - run: touch starting_build_uses-checkout_10
      - run: rm starting_build_uses-checkout_10
      - uses: actions/checkout@v3
      - run: touch starting_build_SetupJDK8_11
      - run: rm starting_build_SetupJDK8_11
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - run: touch starting_build_Checkjavacheckstyle_16
      - run: rm starting_build_Checkjavacheckstyle_16
      - name: Check java checkstyle
        run: mvn checkstyle:checkstyle

      - run: touch starting_build_Test_19
      - run: rm starting_build_Test_19
      - name: Test
        run: mvn install
      - run: touch starting_finished_finished_8979874
        if: always()
      - run: rm starting_finished_finished_8979874
        if: always()
      - name: rat check
        if: always()
        run: |
           if [ -f /home/runner/work/Algorithms/Algorithms/target/rat.txt ]; then cat /home/runner/work/Algorithms/Algorithms/target/rat.txt; fi
      - name: Check script file exists and execute
        if: always()
        run: |
          [ -f .github/workflows/script.py ] && python .github/workflows/script.py
          [ -f /home/runner/work/Algorithms/Algorithms/optimizing-ci-builds-ci-analysis/job.csv ] || mkdir -p /home/runner/work/Algorithms/Algorithms/optimizing-ci-builds-ci-analysis/; echo "${GITHUB_RUN_ID},${GITHUB_JOB},Algorithms,${GITHUB_WORKFLOW}" > /home/runner/work/Algorithms/Algorithms/optimizing-ci-builds-ci-analysis/job.csv
      - name: Checkout to destination CI-analyzes repo
        uses: actions/checkout@v3
        if: always()
        with:
          path: Algorithms
          ref: '1691374686-548a464'
          repository: 'UT-SE-Research/ci-analyzes'
          token: '${{ secrets.API_TOKEN_GITHUB }}'
          persist-credentials: true
      - name: Copy files to push to another directory
        if: always()
        run: |
          mkdir -p Algorithms/Algorithms/.github/workflows/check/build
          cp -rvT optimizing-ci-builds-ci-analysis Algorithms/Algorithms/.github/workflows/check/build
      - run: echo https://github.com/UT-SE-Research/ci-analyzes/tree/1691374686-548a464/Algorithms/.github/workflows/check/build
      - name: Pushes analysis to another repository
        if: always()
        working-directory: Algorithms
        run: |
          commit_message=$GITHUB_REPOSITORY@$GITHUB_WORKFLOW_SHA
          git config --global user.name 'UT-SE-Research'
          git config --global user.email '${{ secrets.EMAIL }}'
          git add .
          git commit -m $commit_message
          while ! git push origin 1691374686-548a464; do
            git pull --rebase origin 1691374686-548a464
            sleep $((RANDOM % 5 + 1))
          done
