name: QA check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install numpy
      - run: sudo apt update
      - run: sudo apt install inotify-tools
      - run: inotifywait -mr /home/runner/work/Algorithms/Algorithms/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
      - run: touch starting_build_uses-checkout_10
      - run: rm starting_build_uses-checkout_10
      - uses: actions/checkout@v3
      - run: touch starting_build_SetupJDK8_11
      - run: rm starting_build_SetupJDK8_11
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - run: touch starting_build_Checkjavacheckstyle_16
      - run: rm starting_build_Checkjavacheckstyle_16
      - name: Check java checkstyle
        run: mvn checkstyle:checkstyle

      - run: touch starting_build_Test_19
      - run: rm starting_build_Test_19
      - name: Test
        run: mvn install
      - run: touch starting_finished_finished_8979874
        if: always()
      - run: rm starting_finished_finished_8979874
        if: always()
      - name: Execute py script # run file
        if: always()
        run: |
          python .github/workflows/script.py
      - name: Pushes analysis to another repository
        if: always()
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'optimizing-ci-builds-ci-analysis'
          destination-github-username: 'optimizing-ci-builds'
          destination-repository-name: 'ci-analyzes'
          target-branch: '1675905814'
          target-directory: 'Algorithms/.github/workflows/check/build'

